/* Autogenerated file. Do not edit manually. */

import { defineComponent, Type as RecsType, World } from '@dojoengine/recs';

export function defineContractComponents(world: World) {
  return {
    Game: (() => {
      return defineComponent(
        world,
        {
          id: RecsType.Number,
          host: RecsType.BigInt,
          over: RecsType.Boolean,
          seed: RecsType.BigInt,
          player_count: RecsType.Number,
          slots: RecsType.Number,
          nonce: RecsType.Number,
        },
        {
          metadata: {
            name: 'Game',
            types: ['u32', 'contractaddress', 'bool', 'felt252', 'u8', 'u8', 'u8'],
            customTypes: [],
          },
        }
      );
    })(),
    Player: (() => {
      return defineComponent(
        world,
        {
          game_id: RecsType.Number,
          index: RecsType.Number,
          address: RecsType.BigInt,
          name: RecsType.BigInt,
          supply: RecsType.Number,
          cards: RecsType.BigInt,
          conqueror: RecsType.Boolean,
        },
        {
          metadata: {
            name: 'Player',
            types: ['u32', 'u32', 'contractaddress', 'felt252', 'u32', 'u128', 'bool'],
            customTypes: [],
          },
        }
      );
    })(),
    Tile: (() => {
      return defineComponent(
        world,
        {
          game_id: RecsType.Number,
          id: RecsType.Number,
          army: RecsType.Number,
          owner: RecsType.Number,
          dispatched: RecsType.Number,
          to: RecsType.Number,
          from: RecsType.Number,
          order: RecsType.BigInt,
        },
        {
          metadata: {
            name: 'Tile',
            types: ['u32', 'u8', 'u32', 'u32', 'u32', 'u8', 'u8', 'felt252'],
            customTypes: [],
          },
        }
      );
    })(),
  };
}
