/* Autogenerated file. Do not edit manually. */

import { defineComponent, Type as RecsType, World } from '@latticexyz/recs';

export function defineContractComponents(world: World) {
  return {
    Game: (() => {
      const name = 'Game';
      return defineComponent(
        world,
        {
          id: RecsType.Number,
          host: RecsType.ContractAddress,
          over: RecsType.Boolean,
          seed: RecsType.Number, // felt252
          player_count: RecsType.Number,
          slots: RecsType.Number,
          nonce: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Player: (() => {
      const name = 'Player';
      return defineComponent(
        world,
        {
          game_id: RecsType.Number,
          index: RecsType.Number,
          address: RecsType.ContractAddress,
          name: RecsType.Number, // felt252
          supply: RecsType.Number,
          cards: RecsType.BigNumber,
          conqueror: RecsType.Boolean,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Tile: (() => {
      const name = 'Tile';
      return defineComponent(
        world,
        {
          game_id: RecsType.Number,
          id: RecsType.Number,
          army: RecsType.Number,
          owner: RecsType.Number,
          dispatched: RecsType.Number,
          to: RecsType.Number,
          from: RecsType.Number,
          order: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    AuthStatus: (() => {
      const name = 'AuthStatus';
      return defineComponent(
        world,
        {
          is_authorized: RecsType.Boolean,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    AuthRole: (() => {
      const name = 'AuthRole';
      return defineComponent(
        world,
        {
          id: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
  };
}
