/* Autogenerated file. Do not edit manually. */

import { defineComponent, Type as RecsType, World } from '@latticexyz/recs';

export function defineContractComponents(world: World) {
  return {
    Game: (() => {
      const name = 'Game';
      return defineComponent(
        world,
        {
          id: RecsType.Number,
          over: RecsType.Number,
          seed: RecsType.Number, // felt252
          player_count: RecsType.Number,
          nonce: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Player: (() => {
      const name = 'Player';
      return defineComponent(
        world,
        {
          address: RecsType.Number, // ContractAddress
          name: RecsType.String,
          supply: RecsType.Number,
          card: RecsType.Number,
          conqueror: RecsType.Boolean,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Tile: (() => {
      const name = 'Tile';
      return defineComponent(
        world,
        {
          army: RecsType.Number,
          owner: RecsType.Number,
          dispatched: RecsType.Number,
          to: RecsType.Number,
          from: RecsType.Number,
          order: RecsType.Number, // felt252
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    AuthStatus: (() => {
      const name = 'AuthStatus';
      return defineComponent(
        world,
        {
          is_authorized: RecsType.Boolean,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    AuthRole: (() => {
      const name = 'AuthRole';
      return defineComponent(
        world,
        {
          id: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
  };
}
